"use strict";
exports.inisiatState = (_a = {},
    _a[{ 1: , "../Imgs/card-1.jpg": , false:  },
        { 2: , "../Imgs/card-2.jpg": , false:  },
        { 3: , "../Imgs/card-3.jpg": , false:  },
        { 4: , "../Imgs/card-4.jpg": , false:  },
        { 5: , "../Imgs/card-5.jpg": , false:  },
        { 6: , "../Imgs/card-6.jpg": , false:  },
        { 7: , "../Imgs/card-7.jpg": , false:  },
        { 8: , "../Imgs/card-8.jpg": , false:  },
        { 9: , "../Imgs/card-1.jpg": , false:  },
        { 10: , "../Imgs/card-2.jpg": , false:  },
        { 11: , "../Imgs/card-3.jpg": , false:  },
        { 12: , "../Imgs/card-4.jpg": , false:  },
        { 13: , "../Imgs/card-5.jpg": , false:  },
        { 14: , "../Imgs/card-6.jpg": , false:  },
        { 15: , "../Imgs/card-7.jpg": , false:  },
        { 15: , "../Imgs/card-8.jpg": , false:  }] = ,
    _a[0] = ,
    _a);
var _a;
